apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: rudyni/inpatient-ufe
  newName: rudyni/inpatient-ufe
  newTag: 1.0.1  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: rudyni/ambulance-wl-webapi
  newName: rudyni/ambulance-wl-webapi
  newTag: 1.0.2

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: mrud-inpatient-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  mrud-inpatient-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1