apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
 app.kubernetes.io/part-of: wac-hospital
 app.kubernetes.io/name: mrud-inpatient-wl

resources:
 - ../../../apps/mrud-inpatient-ufe
 - ../../../apps/mrud-inpatient-webapi


components:
 - ../../../components/version-release