kind: Service
apiVersion: v1
metadata:
  name: mrud-inpatient-openapi-ui
spec:
  selector:
    pod: mrud-inpatient-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081