apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: mrud-inpatient-ufe
spec:
  module-uri: http://mrud-inpatient-ufe.wac-hospital/build/inpatient-ufe.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: mrud-inpatient-wl-app    # element, ktorý bude vložený na stránku
      attributes:
      - name: api-base
        value: /mrud-inpatient-api
      - name: ambulance-id
        value: chira
      path: mrud-inpatient-wl      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Správa ložkových častí      # názov mikro aplikácie
      details: Spravuje zoznam lozkovych casti v nemocnimi pre dane oddelenie
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha2             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach